[server]
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#007bff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#343a40" 